export const platformCapabilities = {
  creation: [
    "AI outline and slide generation",
    "documents, reports and whitepapers",
    "spreadsheet and dashboard generation",
    "infographic-first visual storytelling",
    "poster and social carousel generation",
    "one source to many coordinated outputs",
    "natural-language artifact transformation",
    "presentation director and narrative planning",
    "translation and localization",
    "brand-aware generation",
  ],
  intelligence: [
    "design critic and one-click review guidance",
    "audience simulation",
    "research and evidence planning",
    "content provenance",
    "knowledge-base reuse",
    "data-story recommendations",
    "artifact quality scoring",
    "governance-aware generation",
    "universal semantic content graph",
    "cross-artifact consistency checking",
    "semantic workspace search",
    "linked fact and metric propagation",
    "source freshness and lineage",
  ],
  visuals: [
    "advanced charts and statistical graphics",
    "Sankey, waterfall, treemap, funnel and Gantt charts",
    "flowcharts and swimlanes",
    "architecture and network diagrams",
    "org charts, decision trees and mind maps",
    "timelines, roadmaps and process maps",
    "maps and geospatial storytelling",
    "editable infographic composition",
    "responsive multi-format layouts",
    "constraint-based adaptive layout engine",
    "format-specific reflow for deck print dashboard mobile infographic poster and social",
    "brand-token-aware layout generation",
    "adaptive layout quality auditing",
    "multi-target layout generation and snapshots",
    "multi-candidate constraint solving",
    "relationship-aware visual grouping",
    "whitespace and balance scoring",
    "typography fitting",
    "focal-point-aware image cropping",
    "chart aspect-ratio optimization",
    "iterative layout candidate ranking",
    "in-place visual editing",
    "SAM-style object segmentation",
    "object removal replacement and recoloring",
    "background removal and replacement",
    "non-destructive image edit history",
  ],
  data: [
    "Google Sheets, Excel and CSV",
    "SQL and REST API sources",
    "Airtable and Notion",
    "Power BI and Tableau interoperability",
    "Salesforce and HubSpot",
    "scheduled data refresh",
    "live chart binding",
    "AI data analysis",
    "governed metric definitions",
    "authoritative KPI snapshots",
    "data lineage and freshness status",
  ],
  automation: [
    "trigger-to-output workflow graphs",
    "research analyze design review export pipelines",
    "scheduled report and deck refresh",
    "approval gates",
    "publishing and notifications",
    "bulk generation and mail merge",
    "webhooks and external automation adapters",
  ],
  templates: [
    "large built-in template library",
    "creator template studio",
    "public marketplace",
    "free and paid templates",
    "component marketplace foundation",
    "versioned template packages",
    "reviews ratings and licensing",
    "creator analytics and payouts foundation",
    "template remixing",
    "template and asset fingerprinting",
  ],
  enterprise: [
    "SSO and policy integration foundation",
    "approval workflows",
    "brand governance",
    "content locking",
    "retention and sharing policies",
    "cost and model governance",
    "audit and provenance records",
    "private organizational knowledge",
    "pre-publish quality gates",
    "document classification and watermark policy",
    "controlled publish overrides",
  ],
  publishing: [
    "public and private web publishing",
    "password and expiry controls",
    "custom-domain foundation",
    "viewer engagement analytics",
    "lead capture and forms foundation",
    "A/B experiment variants",
    "downloads and sharing analytics",
  ],
  collaboration: [
    "workspaces and organizations",
    "RBAC",
    "comments and threads",
    "version history",
    "sharing controls",
    "audit logs",
  ],
  platform: [
    "model routing",
    "usage metering",
    "API credentials",
    "webhooks",
    "brand kits",
    "multi-format exports",
    "admin controls",
  ],
} as const;

export type CapabilityGroup = keyof typeof platformCapabilities;
