export const platformCapabilities = {
  creation: [
    "AI outline and slide generation",
    "documents, reports and whitepapers",
    "spreadsheet and dashboard generation",
    "infographic-first visual storytelling",
    "poster and social carousel generation",
    "one source to many coordinated outputs",
    "natural-language artifact transformation",
    "presentation director and narrative planning",
    "translation and localization",
    "brand-aware generation",
  ],
  intelligence: [
    "design critic and one-click review guidance",
    "audience simulation",
    "research and evidence planning",
    "content provenance",
    "knowledge-base reuse",
    "data-story recommendations",
    "artifact quality scoring",
    "governance-aware generation",
  ],
  visuals: [
    "advanced charts and statistical graphics",
    "Sankey, waterfall, treemap, funnel and Gantt charts",
    "flowcharts and swimlanes",
    "architecture and network diagrams",
    "org charts, decision trees and mind maps",
    "timelines, roadmaps and process maps",
    "maps and geospatial storytelling",
    "editable infographic composition",
    "responsive multi-format layouts",
  ],
  data: [
    "Google Sheets, Excel and CSV",
    "SQL and REST API sources",
    "Airtable and Notion",
    "Power BI and Tableau interoperability",
    "Salesforce and HubSpot",
    "scheduled data refresh",
    "live chart binding",
    "AI data analysis",
  ],
  automation: [
    "trigger-to-output workflow graphs",
    "research analyze design review export pipelines",
    "scheduled report and deck refresh",
    "approval gates",
    "publishing and notifications",
    "bulk generation and mail merge",
    "webhooks and external automation adapters",
  ],
  templates: [
    "large built-in template library",
    "creator template studio",
    "public marketplace",
    "free and paid templates",
    "component marketplace foundation",
    "versioned template packages",
    "reviews ratings and licensing",
    "creator analytics and payouts foundation",
  ],
  enterprise: [
    "SSO and policy integration foundation",
    "approval workflows",
    "brand governance",
    "content locking",
    "retention and sharing policies",
    "cost and model governance",
    "audit and provenance records",
    "private organizational knowledge",
  ],
  publishing: [
    "public and private web publishing",
    "password and expiry controls",
    "custom-domain foundation",
    "viewer engagement analytics",
    "lead capture and forms foundation",
    "A/B experiment variants",
    "downloads and sharing analytics",
  ],
  collaboration: [
    "workspaces and organizations",
    "RBAC",
    "comments and threads",
    "version history",
    "sharing controls",
    "audit logs",
  ],
  platform: [
    "model routing",
    "usage metering",
    "API credentials",
    "webhooks",
    "brand kits",
    "multi-format exports",
    "admin controls",
  ],
} as const;

export type CapabilityGroup = keyof typeof platformCapabilities;
