export const platformCapabilities = {
  creation: [
    "AI outline and slide generation",
    "documents, reports and whitepapers",
    "spreadsheet and dashboard generation",
    "infographic-first visual storytelling",
    "poster and social carousel generation",
    "presentation director",
    "speaker notes",
    "slide expansion and compression",
    "automatic narrative planning",
    "translation and localization",
    "brand-aware generation",
  ],
  visuals: [
    "bar, line, area, scatter and statistical charts",
    "Sankey, waterfall, treemap, funnel and Gantt charts",
    "flowcharts and swimlanes",
    "architecture and network diagrams",
    "org charts, decision trees and mind maps",
    "timelines, roadmaps and process maps",
    "maps and geospatial storytelling",
    "editable infographic composition",
  ],
  research: [
    "PDF, Office, CSV, URL and media ingestion",
    "RAG and source retrieval",
    "citation-aware generation",
    "fact-check workflow",
    "web research adapters",
    "data-to-chart recommendations",
  ],
  templates: [
    "large built-in template library",
    "creator template studio",
    "public marketplace",
    "free and paid templates",
    "versioned template packages",
    "reviews and ratings",
    "template licensing",
    "creator analytics and payouts foundation",
  ],
  collaboration: [
    "workspaces and organizations",
    "RBAC",
    "comments and threads",
    "version history",
    "sharing controls",
    "audit logs",
  ],
  platform: [
    "model routing",
    "usage metering",
    "API credentials",
    "webhooks",
    "brand kits",
    "multi-format exports",
    "admin controls",
  ],
} as const;

export type CapabilityGroup = keyof typeof platformCapabilities;
